name: student_projectry_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  http: ^1.4.0
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  http: ^1.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Mentor logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
