// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAha8PwfaqmlxaHt4i7bC4bIq7prS77HNY',
    appId: '1:244649402555:web:7f3e96ff561724a731499e',
    messagingSenderId: '244649402555',
    projectId: 'employee-directory-app-17382',
    authDomain: 'employee-directory-app-17382.firebaseapp.com',
    storageBucket: 'employee-directory-app-17382.firebasestorage.app',
    measurementId: 'G-XYPHY84ZXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZZ8TYGHS6jvmTAK7FiXEhNQhcujIdU8',
    appId: '1:244649402555:android:8b8c0cc24b36e88031499e',
    messagingSenderId: '244649402555',
    projectId: 'employee-directory-app-17382',
    storageBucket: 'employee-directory-app-17382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlfs14KOPPPZ6WamnJd2hxL2ChYAbiajs',
    appId: '1:244649402555:ios:3007ef869ef6389731499e',
    messagingSenderId: '244649402555',
    projectId: 'employee-directory-app-17382',
    storageBucket: 'employee-directory-app-17382.firebasestorage.app',
    iosBundleId: 'com.example.studentProjectryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlfs14KOPPPZ6WamnJd2hxL2ChYAbiajs',
    appId: '1:244649402555:ios:3007ef869ef6389731499e',
    messagingSenderId: '244649402555',
    projectId: 'employee-directory-app-17382',
    storageBucket: 'employee-directory-app-17382.firebasestorage.app',
    iosBundleId: 'com.example.studentProjectryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAha8PwfaqmlxaHt4i7bC4bIq7prS77HNY',
    appId: '1:244649402555:web:281184a95a1fd71731499e',
    messagingSenderId: '244649402555',
    projectId: 'employee-directory-app-17382',
    authDomain: 'employee-directory-app-17382.firebaseapp.com',
    storageBucket: 'employee-directory-app-17382.firebasestorage.app',
    measurementId: 'G-5KFVVYFF5T',
  );
}
